### ISSUE TITLE
Simulation and UKB scripts of article?

### ISSUE THREAD

**Issue by richelbilderbeek** [taylorcavazos/PRS_Admixture_Simulation#1] opened 2021-09-09 07:36 UTC
Hi @taylorcavazos,

Today we discussed your article that the code in the repo applies to [1]. I am always very happy to see code, as it is part of the idea that science should be reproducible.

What I miss, however, are the scripts used to do the simulation runs, create the pictures as well as the UK Biobank analysis.

I feel it would be nice to have these somewhere public as well, so our colleagues can reproduce your (great!) findings.

Are there plans to release these as well publicly?

Thanks and cheers, Richel Bilderbeek

 * [1] Cavazos and Witte, Inclusion of Variants Discovered from Diverse Populations Improves Polygenic Risk Score Transferability, HGG Advances 2020

**Comment by taylorcavazos** [comment] 2021-09-09 15:39
Hi @richelbilderbeek,

Thank you for your interest in our work!

If you want to reproduce the simulations from our paper this can be done using the available code:

```
conda activate prs_sim
python run_simulation.py --sim 1 --snp_selection ceu --snp_weighting ceu
conda deactivate
```

To follow our analysis pipeline you would repeat this block 50x for each `snp_selection` and `snp_weighting` strategy. For our paper we used: `snp_selection` = {ceu, yri, meta}, `snp_weighting` = {ceu, yri, meta, la}

**Comment by taylorcavazos** [comment] 2021-09-09 16:07
Hi @richelbilderbeek,

Thank you for your interest in our work! I'll do my best to address your questions, but please let me know if I'm missing anything. 

As you point out correctly, **the goal of this repository is to provide users flexibility to run their own simulations using our framework and less so to reproduce the results from our paper**. With that being said, using this code + publicly available software (UKB analysis) you can definitely reproduce all of our findings.

#### Part 1: Simulations
If you want to reproduce the simulations from our paper this can be done using the available code:

```
conda activate prs_sim
python run_simulation.py --sim 1 --snp_selection ceu --snp_weighting ceu
conda deactivate
```
To follow our analysis pipeline you would repeat this block 50x for each `snp_selection` and `snp_weighting` strategy. For our paper we used: `snp_selection` = {ceu, yri, meta}, `snp_weighting` = {ceu, yri, meta, la}

I don't provide a script for this because I want users to have flexibility to distribute these tasks on a HPC machine. Running each of these simulations one-at-a-time would be very time-consuming.

*Note: In our publication we also vary # of causal variants (`--m`), heritability (`--h2`), PRS building parameters (`--pvalue` & `--ld_r2`), and the number of YRI samples used in the analysis ( `--decrease_samples_yri`). All parameters explored in our publication can easily be reproduced using the specified flags.*

#### Part 2: Paper Figures

The output of the simulation will generate all data necessary for creating paper figures. If helpful, I am happy to add figure code in a subfolder in this repository; however, this will take some time to format for sharing and make sure it can be easily ran by others.

#### Part 3: UK Biobank Analysis

All software needed to perform the UKB analysis is publicly available and linked in the publication. I have hesitations about including my personal UKB analysis scripts here for many reasons including: they are formatted for my specific HPC environment, assume software is downloaded, and use hard-coded paths to local data. Overall, I do not think they are necessary for reproducing the results; however, please let me know if you have suggestions or thoughts on this!

**Comment by richelbilderbeek** [comment] 2021-09-10 05:48
Hi @taylorcavazos,

Thanks for the reply! As this is a 'no', I will try again:

Too bad you don't post those the scripts to run the simulation (sure, I can read what you did in the paper), how you created the plots (I assume you did not draw these by hands) nor the UKB analysis. I understand that parts of scripts are specific to a computer cluster, and have assumptions about the environment and probably such scripts are sloppy. 

Still, adding those scripts would allow me to reproduce your work from. Or get a precise idea of your settings. How much HPC memory it cost. It has value.

I hope you put those those scripts online somewhere (I -probably like you- like to use a different GitHub repo for the HPC scripts, e.g. [here](https://github.com/richelbilderbeek/ncbi_peregrine/tree/master/scripts)). I would enjoy seeing those bad jokes in your scripts, like most people have :-)

**Comment by taylorcavazos** [comment] 2021-12-03 16:33
Closing this issue for now! Will work on uploading scripts to replicate the paper, but it will not be contained in this repo (for ease of simulation use). Will reach out when everything is uploaded and I will link to the new repo in this repo. Thanks again for your interest in our work.

Best,
Taylor

**Closed as completed by taylorcavazos** 2021-12-03 16:33 UTC
